name       : marp-cli
version    : 3.2.0
release    : 6
homepage   : https://marp.app/
source     :
    - https://github.com/marp-team/marp-cli/archive/refs/tags/v3.2.0.tar.gz : c24f0733eb1f15799c481aa191db019929a5daa656ece026749291576d6a44c0
license    : MIT
component  : office
networking : yes
strip      : no
summary    : A CLI interface for Marp and Marpit based converters
description: |
    A CLI interface for Marp and any slide deck converter based on Marpit framework. It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.
builddeps  :
    - yarn
setup      : |
    yarn install
build      : |
    yarn build
    yarn run pkg . \
        --out-path ./bin \
        --targets host \
        --compress Brotli
install    : |
    install -Dm0755 bin/marp-cli $installdir/usr/bin/marp
