name       : marp-cli
version    : 2.2.0
release    : 1
homepage   : https://marp.app/
source     :
    - https://github.com/marp-team/marp-cli/archive/refs/tags/v2.2.0.tar.gz : 94bcf1cab42b3e57f405346ac797b9520f9238878be6cee32b5cc22444a8eaeb
license    : MIT
component  : office
networking : yes
strip      : no
summary    : A CLI interface for Marp and Marpit based converters
description: |
    A CLI interface for Marp and any slide deck converter based on Marpit framework. It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.
builddeps  :
    - yarn
setup      : |
    yarn install
build      : |
    yarn build
    yarn run pkg . \
        --out-path ./bin \
        --targets host \
        --compress Brotli
install    : |
    install -Dm0755 bin/marp-cli $installdir/usr/bin/marp
