name       : marp-cli
version    : 3.1.0
release    : 5
homepage   : https://marp.app/
source     :
    - https://github.com/marp-team/marp-cli/archive/refs/tags/v3.0.2.tar.gz : bcee43729b7ecce1762616eeda02c209522fb9a3c414e534a894b7d607a5f4d6
license    : MIT
component  : office
networking : yes
strip      : no
summary    : A CLI interface for Marp and Marpit based converters
description: |
    A CLI interface for Marp and any slide deck converter based on Marpit framework. It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.
builddeps  :
    - yarn
setup      : |
    yarn install
build      : |
    yarn build
    yarn run pkg . \
        --out-path ./bin \
        --targets host \
        --compress Brotli
install    : |
    install -Dm0755 bin/marp-cli $installdir/usr/bin/marp
